name: CI/CD Production Frontend-Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-ci-cd:
    uses: ./.github/workflows/ci-cd.yml
    with:
      project: "ttsopenai"
      service_name: "docs"
      env_code: "prod"
      environment: "Production"
      git_branch: "main"
      aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
      aws_region: ${{ vars.AWS_REGION }}
      slack_mentions: ${{ vars.SLACK_MENTIONS }}
      slack_webhook_url: ${{ vars.SLACK_WEBHOOK_URL }}
    secrets: inherit